INSERT INTO reflexpr.operation
(result, operation_name, operation_overload)
VALUES('BooleanConstant', 'reflects_same', 'Object');

INSERT INTO reflexpr.operation_parameter
(operation_name, operation_overload, position, parameter)
VALUES('reflects_same', 'Object', 0, 'Object');

INSERT INTO reflexpr.operation_parameter
(operation_name, operation_overload, position, parameter)
VALUES('reflects_same', 'Object', 1, 'Object');
