INSERT INTO reflexpr.operation
(result, operation_name, operation_overload)
VALUES('BaseLevelType', 'unpack_sequence', 'ObjectSequence');

INSERT INTO reflexpr.operation_parameter
(operation_name, operation_overload, position, parameter)
VALUES('unpack_sequence', 'ObjectSequence', 0, 'UnpackTemplate');

INSERT INTO reflexpr.operation_parameter
(operation_name, operation_overload, position, parameter)
VALUES('unpack_sequence', 'ObjectSequence', 1, 'ObjectSequence');
