INSERT INTO reflexpr.operation
(result, operation_name, operation_overload)
VALUES('Object', 'get_element', 'ObjectSequence');

INSERT INTO reflexpr.operation_parameter
(operation_name, operation_overload, position, parameter)
VALUES( 'get_element', 'ObjectSequence', 0, 'IntegerConstant');

INSERT INTO reflexpr.operation_parameter
(operation_name, operation_overload, position, parameter)
VALUES('get_element', 'ObjectSequence', 1, 'ObjectSequence');
