INSERT INTO reflexpr.operation
(result, operation_name, operation_overload)
VALUES('BooleanConstant', 'is_final', 'Class');

INSERT INTO reflexpr.simple_operation_parameter
(operation_name, parameter)
VALUES('is_final', 'Class');

INSERT INTO reflexpr.operation
(result, operation_name, operation_overload)
VALUES('BooleanConstant', 'is_final', 'MemberFunction');

INSERT INTO reflexpr.simple_operation_parameter
(operation_name, parameter)
VALUES('is_final', 'MemberFunction');
