INSERT INTO reflexpr.operation
(result, operation_name, operation_overload)
VALUES('BooleanConstant', 'is_private', 'RecordMember');

INSERT INTO reflexpr.simple_operation_parameter
(operation_name, parameter)
VALUES('is_private', 'RecordMember');

INSERT INTO reflexpr.operation
(result, operation_name, operation_overload)
VALUES('BooleanConstant', 'is_private', 'Base');

INSERT INTO reflexpr.simple_operation_parameter
(operation_name, parameter)
VALUES('is_private', 'Base');
